from typing import Protocol

class GamePlatform(Protocol):
    def screenshot(self) -> bytes: ...
    def tap(self, x: int, y: int) -> None: ...
    def swipe(self, x1: int, y1: int, x2: int, y2: int, duration_ms: int = 650) -> None: ...
    def hide(self) -> None: ...
    def show(self) -> None: ...
